<script lang="ts">
  import { VERSION } from '$lib/version';
</script>

<svelte:head>
  <title>Privacy Policy - n of m</title>
</svelte:head>

<div class="privacy">
  <header class="privacy-header">
    <a href="/" class="back-link"><i class="fa-thin fa-arrow-left"></i> Back to App</a>
    <h1>Privacy Policy</h1>
    <p class="text-muted text-sm">Last updated: February 28, 2026</p>
  </header>

  <section class="privacy-section">
    <h2>Introduction</h2>
    <p>
      This Privacy Policy describes how the "n of m" application ("the App") handles
      your information. The App implements Shamir's Secret Sharing for splitting and
      recovering seed phrases. Your privacy is fundamental to the App's design.
    </p>
  </section>

  <section class="privacy-section">
    <h2>Data Collection</h2>
    <p><strong>The App does not collect, transmit, or store any personal data on external servers.</strong></p>
    <p>Specifically, the App does <strong>not</strong> collect:</p>
    <ul>
      <li>Names, email addresses, or contact information</li>
      <li>Device identifiers or advertising IDs</li>
      <li>Location data</li>
      <li>Usage analytics or telemetry</li>
      <li>Crash reports sent to external services</li>
    </ul>
  </section>

  <section class="privacy-section">
    <h2>Local Data Storage</h2>
    <p>
      All data generated by the App -- including seed phrases, secret shares, vault
      configurations, and encryption keys -- is stored <strong>exclusively on your device</strong>
      using the browser's local storage or the device's native storage.
    </p>
    <p>
      No data ever leaves your device unless you explicitly choose to export it
      (e.g., printing share cards, saving PDF files, or exporting vault backups).
    </p>
  </section>

  <section class="privacy-section">
    <h2>Camera Access</h2>
    <p>
      The App may request access to your device's camera solely for the purpose of
      scanning QR codes during share recovery. Camera data is processed entirely
      on-device and is never recorded, stored, or transmitted.
    </p>
  </section>

  <section class="privacy-section">
    <h2>Third-Party Services</h2>
    <p>
      The App does not integrate with any third-party analytics, advertising, or
      tracking services. No data is shared with third parties.
    </p>
  </section>

  <section class="privacy-section">
    <h2>Encryption</h2>
    <p>
      When you use the vault feature, your data is encrypted locally using AES-256-GCM
      with a password you provide. The encryption and decryption occur entirely on your
      device. Your password is never stored or transmitted.
    </p>
  </section>

  <section class="privacy-section">
    <h2>Children's Privacy</h2>
    <p>
      The App is not directed at children under the age of 13 and does not knowingly
      collect any information from children.
    </p>
  </section>

  <section class="privacy-section">
    <h2>Changes to This Policy</h2>
    <p>
      This Privacy Policy may be updated from time to time. Any changes will be
      reflected on this page with an updated revision date. Continued use of the
      App after changes constitutes acceptance of the revised policy.
    </p>
  </section>

  <section class="privacy-section">
    <h2>Contact</h2>
    <p>
      If you have questions about this Privacy Policy, please open an issue on the
      App's <a href="https://github.com/tankbottoms/n-of-m-web" target="_blank" rel="noopener">GitHub repository</a>.
    </p>
  </section>

  <footer class="privacy-footer">
    <p class="text-muted text-sm">n of m v{VERSION}</p>
  </footer>
</div>

<style>
  .privacy {
    max-width: 720px;
    margin: 0 auto;
    padding: var(--spacing-lg);
    font-family: var(--font-mono);
  }

  .privacy-header {
    margin-bottom: var(--spacing-xl);
    padding-bottom: var(--spacing-md);
    border-bottom: 1px solid var(--color-border);
  }

  .privacy-header h1 {
    margin: var(--spacing-sm) 0 var(--spacing-xs);
    font-size: 1.5rem;
  }

  .back-link {
    font-size: 0.85rem;
    color: var(--color-text-muted);
    text-decoration: none;
  }

  .back-link:hover {
    color: var(--color-text);
  }

  .privacy-section {
    margin-bottom: var(--spacing-xl);
  }

  .privacy-section h2 {
    font-size: 1.1rem;
    margin-bottom: var(--spacing-sm);
    border-bottom: 1px solid var(--color-border-light);
    padding-bottom: var(--spacing-xs);
  }

  .privacy-section p {
    margin-bottom: var(--spacing-sm);
    line-height: 1.6;
    font-size: 0.9rem;
    color: var(--color-text);
  }

  .privacy-section ul {
    margin: var(--spacing-sm) 0;
    padding-left: var(--spacing-lg);
  }

  .privacy-section li {
    margin-bottom: var(--spacing-xs);
    line-height: 1.5;
    font-size: 0.9rem;
    color: var(--color-text);
  }

  .privacy-section a {
    color: var(--color-link);
  }

  .privacy-footer {
    margin-top: var(--spacing-xl);
    padding-top: var(--spacing-md);
    border-top: 1px solid var(--color-border);
    text-align: center;
  }

  .text-muted {
    color: var(--color-text-muted);
  }

  .text-sm {
    font-size: 0.8rem;
  }
</style>
