export const WORDS: string[] = [
  "ace", "age", "aid", "aim", "air", "ant", "ape", "arc", "arm", "art",
  "ash", "ask", "axe", "bay", "bed", "bee", "big", "bit", "bow", "box",
  "boy", "bud", "bug", "bus", "buy", "cab", "cam", "can", "cap", "car",
  "cat", "cob", "cod", "cog", "cop", "cow", "cry", "cub", "cup", "cur",
  "cut", "dam", "day", "den", "dew", "did", "dig", "dim", "dip", "doe",
  "dog", "dot", "dry", "dub", "dud", "due", "dug", "dun", "duo", "dye",
  "ear", "eat", "eel", "egg", "ego", "elk", "elm", "emu", "end", "era",
  "eve", "ewe", "eye", "fan", "far", "fat", "fax", "fed", "few", "fig",
  "fin", "fir", "fit", "fix", "fly", "foe", "fog", "for", "fox", "fry",
  "fun", "fur", "gag", "gap", "gas", "gel", "gem", "get", "gin", "gnu",
  "god", "got", "gum", "gun", "gut", "guy", "gym", "had", "ham", "hat",
  "hay", "hen", "her", "hew", "hex", "hid", "him", "hip", "hit", "hog",
  "hop", "hot", "how", "hub", "hue", "hug", "hum", "hut", "ice", "icy",
  "ill", "imp", "ink", "inn", "ion", "ire", "irk", "ivy", "jab", "jag",
  "jam", "jar", "jaw", "jay", "jet", "jig", "job", "jog", "jot", "joy",
  "jug", "key", "kid", "kin", "kit", "lab", "lad", "lag", "lap", "law",
  "lay", "lea", "led", "leg", "let", "lid", "lip", "lit", "log", "lot",
  "low", "lug", "mad", "man", "map", "mat", "maw", "may", "men", "met",
  "mix", "mob", "mod", "mop", "mud", "mug", "nab", "nag", "nap", "net",
  "new", "nil", "nip", "nit", "nod", "nor", "not", "now", "nun", "nut",
  "oak", "oar", "oat", "odd", "ode", "off", "oft", "ohm", "oil", "old",
  "one", "opt", "orb", "ore", "our", "out", "owe", "owl", "own", "pad",
  "pan", "paw", "pay", "pea", "peg", "pen", "per", "pet", "pie", "pig",
  "pin", "pit", "ply", "pod", "pop", "pot", "pow", "pry", "pub", "pug",
  "pun", "pup", "put", "rag", "ram", "ran", "rap", "rat", "raw", "ray",
  "red", "rib", "rid", "rig", "rim", "rip", "rob", "rod", "roe", "rot",
  "row", "rub", "rug", "rum", "run", "rut", "rye", "sac", "sad", "sag",
  "sap", "sat", "saw", "say", "sea", "set", "sew", "shy", "sin", "sip",
  "sir", "sis", "sit", "six", "ski", "sky", "sly", "sob", "sod", "son",
  "sop", "sot", "sow", "soy", "spa", "spy", "sub", "sum", "sun", "sup",
  "tab", "tad", "tag", "tan", "tap", "tar", "tax", "tea", "ten", "the",
  "thy", "tic", "tie", "tin", "tip", "toe", "ton", "too", "top", "tow",
  "toy", "try", "tub", "tug", "two", "urn", "use", "van", "vat", "vet",
  "via", "vie", "vim", "vow", "wad", "wag", "war", "was", "wax", "way",
  "web", "wed", "wet", "who", "why", "wig", "win", "wit", "woe", "wok",
  "won", "woo", "wow", "yak", "yam", "yap", "yaw", "yea", "yes", "yet",
  "yew", "you", "zap", "zen", "zig", "zip", "zoo",
];

export function getRandomWord(): string {
  return WORDS[Math.floor(Math.random() * WORDS.length)]!;
}
